layout_spectrum: 0.4425532
color:
  saturation: 0.3775892
  brandStrength: 0.940727
  lightness: 0.312766
  rhythmicContrast: 0.8682558
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.393617
name: V1
